# Generated by Django 4.0.1 on 2022-02-20 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_project_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('Can add user', 'Может добавлять пользователей в проект')], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
    ]
