# Generated by Django 4.0.1 on 2022-02-20 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('can_add_user', 'Может добавлять пользователей в проект')], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
    ]
